<script type="text/ng-template" id="adminStripDelete">
<div ng-controller="StripDeleteController">
    <form name="adminStripsDelete">
        <h2><?= $this->translate('Confirm strip deletion'); ?></h2>
        <div class="row">
            <div class="form-group col-lg-12">
                <p><?= $this->translate('Are you sure?'); ?></p>
                <p><?= $this->translate('This action will remove strip along with images.'); ?></p>
                <p><?= $this->translate('Please confirm it\'s what you want.'); ?></p>
            </div>
            <div class="form-group col-lg-12 actions">
                <button class="btn btn-danger strip-delete-confirm" ng-click="delete()" ng-disabled="strips.loading || closing">
                    <?= $this->translate('I understand, delete, please'); ?>
                </button>
                <button class="btn btn-primary pull-left strips-delete-cancel" ng-click="cancel()" ng-disabled="strips.loading || closing">
                    <?= $this->translate('Cancel'); ?>
                </button>
        </div>
    </form>
</div>
</script>
