<script type="text/ng-template" id="adminStripsList">
<div class="panel panel-default" ng-controller="StripsController">
    <h2 class="panel-heading">
        <button
            type="button"
            class="btn btn-success pull-right create-strip"
            ng-click="new()"
            ng-disabled="strips.editing() || strips.loadingEntity"
        >
            <?= $this->translate("Create strip") ?>
        </button>
        <?= $this->translate('Strips'); ?>
    </h2>
    <div class="panel-body">
        <dir-pagination-controls
            ng-show="!strips.loading"
            on-page-change="strips.changePage(newPageNumber)"
            template-url="adminStripsListPagination"
            pagination-id="'strips'"
        >
        </dir-pagination-controls>

        <ul class="list-group strips" ng-show="strips.loaded">
            <li
                dir-paginate="entity in strips.list | itemsPerPage: strips.limit"
                pagination-id="'strips'"
                total-items="strips.total"
                current-page="strips.current"
                class="list-group-item"
                ng-class="{active: activated(entity)}"
                ng-click="activate(entity)"
                >
                <div class="clearfix row">
                    <div class="col-md-8">
                        <h3 class="title" ng-bind="entity.title"></h3>
                    </div>
                    <div class="col-md-4 media-right">
                        <img ng-src="{{ entity.cover }}" class="thumbnail">
                    </div>
                </div>
            </li>
        </ul>
        <div ng-show="strips.list.length === 0 && strips.loaded">
                <?= sprintf(
                    $this->translate("%s does not have any strips yet."),
                    '<span ng-bind-html="$parent.getActive().title | bold"></span>'
                ); ?>
        </div>

        <div ng-show="!strips.loaded" ng-include="'loading'"></div>

        <dir-pagination-controls
            ng-show="!strips.loading"
            on-page-change="strips.changePage(newPageNumber)"
            template-url="adminStripsListPagination"
            pagination-id="'strips'"
        >
        </dir-pagination-controls>
    </div>
</div>
</script>