<script type="text/ng-template" id="adminStripsListPagination">
<ul class="pagination" ng-if="1 < pages.length">
    <li ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 || $root.disableStripsPagination() }">
        <a ng-show="!$root.disableStripsPagination()" href="" ng-click="setCurrent(1)">&laquo;</a>
        <a ng-show="$root.disableStripsPagination()" ng-click="$root.showStripPaginationErrorEntityEditInProgress()" href="">&laquo;</a>
    </li>
    <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 || $root.disableStripsPagination() }">
        <a ng-show="!$root.disableStripsPagination()" href="" ng-click="setCurrent(pagination.current - 1)">&lsaquo;</a>
        <a ng-show="$root.disableStripsPagination()" ng-click="$root.showStripPaginationErrorEntityEditInProgress()" href="">&lsaquo;</a>
    </li>
    <li ng-repeat="pageNumber in pages track by $index" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == '...' || $root.disableStripsPagination() }">
        <a ng-show="!$root.disableStripsPagination()" href="" ng-click="setCurrent(pageNumber)">{{ pageNumber }}</a>
        <a ng-show="$root.disableStripsPagination()" ng-click="$root.showStripPaginationErrorEntityEditInProgress()" href="">{{ pageNumber }}</a>
    </li>
    <li ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last || $root.disableStripsPagination() }">
        <a ng-show="!$root.disableStripsPagination()" href="" ng-click="setCurrent(pagination.current + 1)">&rsaquo;</a>
        <a ng-show="$root.disableStripsPagination()" ng-click="$root.showStripPaginationErrorEntityEditInProgress()" href="">&rsaquo;</a>
    </li>
    <li ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last || $root.disableStripsPagination() }">
        <a ng-show="!$root.disableStripsPagination()" href="" ng-click="setCurrent(pagination.last)">&raquo;</a>
        <a ng-show="$root.disableStripsPagination()" ng-click="$root.showStripPaginationErrorEntityEditInProgress()" href="">&raquo;</a>
    </li>
</ul>
</script>
