<script type="text/ng-template" id="adminStripUpload">
<div ng-controller="StripUploadController">
    <div
        ngf-drop
        ng-model="images"
        class="dropzone"
        ngf-multiple="true"
        ngf-allow-dir="true"
        ngf-select
        ngf-keep="true"
        ngf-keep-distinct="true"
        ngf-accept="'image/*'"
        ngf-drag-over-class="{accept:'accept', reject:'reject', delay:30}"
    ><?= $this->translate('Drop files here, or click to upload'); ?>
        <div ngf-no-file-drop>
            <?= $this->translate('Note: drag & drop upload is not supported by your browser.'); ?>
        </div>
    </div>

    <ul class="list-group">
        <div class="media list-group-item" ng-repeat="image in images">
            <div class="progress" ng-show="!image.loaded">
                <div class="progress-bar" role="progressbar" aria-valuenow="{{ image.progressPercentage }}" aria-valuemin="0" aria-valuemax="100" ng-style="{'width': image.progressPercentage + '%'}">
                </div>
            </div>
            <div class="manipulation" ng-show="image.loaded">
                <div class="pull-right" ng-class="{'btn-group': loadedFilesLength() > 1}">
                    <button
                        class="btn btn-primary"
                        ng-show="loadedFilesLength() > 1"
                        ng-disabled="images.indexOf( image ) === 0 || strips.saving"
                        ng-click="move('up', image)"
                    ><?= $this->translate('Move up'); ?></button>
                    <button
                        class="btn btn-primary"
                        ng-show="loadedFilesLength() > 1"
                        ng-disabled="images.indexOf( image ) === images.length - 1 || strips.saving"
                        ng-click="move('down', image)"
                    ><?= $this->translate('Move down'); ?></button>
                    <button
                        class="btn btn-danger"
                        ng-click="delete( image )"
                        ng-disabled="strips.saving"
                    ><?= $this->translate('Delete'); ?></button>
                </div>
            </div>
            <div class="media-left" ng-show="image.loaded">
                <a href="javascript:void(0)" class="thumbnail">
                    <img ng-attr-src="{{ image.entity.uri }}" class="media-object">
                </a>
            </div>
            <div class="media-body" ng-show="image.loaded">
                <div class="caption">
                    <textarea
                        class="form-control"
                        ng-model="image.caption"
                        ng-disabled="strips.saving"
                        placeholder="<?= $this->translate('Caption, transcript, description, or leave empty'); ?>"
                    ></textarea>
                </div>
            </div>
        </div>
    </ul>
</div>
</script>