language: php
php:
  - 5.4
addons:
  postgresql: "9.3"
install:
  - composer install
before_script:
  - cp config/autoload/travis.php config/autoload/local.php
  - psql -c 'create database comiccms;' -U postgres
  - vendor/bin/phinx migrate -e development -c phinx.travis.yml
  - vendor/bin/robo createadmin admin@example.com password
  - gem install sass
  - npm install -g bower grunt-cli
  - npm install
  - bower install
  - grunt sass
script:
  - vendor/bin/phpunit
after_success:
  - vendor/bin/coveralls -v
