language: php
php:
  - 5.4
addons:
  postgresql: "9.3"
install:
  - composer install
before_script:
  - psql -c "CREATE USER comiccms WITH PASSWORD '';" -U postgres
  - psql -c 'create database comicmcs;' -U comiccms
  - vendor/bin/phinx migrate -e development
  - vendor/bin/robo createadmin admin@example.com password
  - gem install sass
  - npm install -g bower
  - bower install
  - grunt sass
script:
  - vendor/bin/phpunit