language: php
php:
  - 5.4
addons:
  postgresql: "9.3"
install:
  - composer install --no-interaction --dev
before_script:
  - cp config/autoload/travis.php config/autoload/local.php
  - psql -c 'create database comiccms;' -U postgres
  - vendor/bin/doctrine migrations:migrate -n
  - vendor/bin/robo createadmin admin@example.com password
  - gem install sass
  - npm install -g bower grunt-cli
  - npm install
  - bower install
  - grunt sass
script:
  - vendor/bin/phpunit
after_success:
  - php vendor/bin/coveralls -v
