<script type="text/ng-template" id="adminComicsEdit">
<div ng-controller="ComicEditController">
    <form name="adminComicsEdit">
        <h2><?= $this->translate('Create comics'); ?></h2>
        <div class="row">
            <div class="form-group col-sm-6">
                <label for="comics-title"><?= $this->translate('Title (required):'); ?></label>
                <input
                    class="form-control"
                    type="text"
                    name="comics-title"
                    id="comics-title"
                    ng-required="true"
                    ng-trim="true"
                    ng-minlength="1"
                    focus-once="true"
                    ng-model="comics.editedEntity.title"
                    ng-disabled="comics.loading"
                >
            </div>
            <div class="form-group col-sm-6">
                <label for="comics-slug"><?= $this->translate('Slug (required):'); ?></label>
                <input
                    class="form-control"
                    type="text"
                    name="comics-slug"
                    id="comics-slug"
                    ng-required="true"
                    ng-trim="true"
                    ng-minlength="1"
                    ng-model="comics.editedEntity.slug.slug"
                    ng-disabled="comics.loading"
                >
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-6">
                <label for="comics-tagline"><?= $this->translate('Tagline (optional):'); ?></label>
                <input
                    class="form-control"
                    type="text"
                    name="comics-tagline"
                    id="comics-tagline"
                    ng-model="comics.editedEntity.tagline"
                    ng-disabled="comics.loading"
                >
            </div>
            <div class="form-group col-sm-6">
                <label for="comics-author"><?= $this->translate('Author (optional):'); ?></label>
                <input
                    class="form-control"
                    type="text"
                    name="comics-author"
                    id="comics-author"
                    ng-model="comics.editedEntity.author"
                    ng-disabled="comics.loading"
                >
            </div>
        </div>
        <div class="row">
        <div class="form-group col-sm-12">
            <label for="comics-description"><?= $this->translate('Description (optional):'); ?></label>
            <textarea
                class="form-control"
                type="text"
                name="comics-description"
                id="comics-description"
                ng-model="comics.editedEntity.description"
                ng-disabled="comics.loading"
            ></textarea>
        </div>
        </div>
        <div class="form-group actions">
            <button
                class="btn btn-success pull-right comics-create"
                ng-click="save()"
                ng-disabled="adminComicsEdit.$invalid || comics.loading"
                ng-show="comics.editingNew()"
            ><?= $this->translate('Create'); ?></button>
            <button
                class="btn btn-success pull-right comics-save"
                ng-click="save()"
                ng-disabled="adminComicsEdit.$invalid || comics.loading"
                ng-show="!comics.editingNew()"
            ><?= $this->translate('Save'); ?></button>
            <button
                class="btn btn-danger pull-left comics-dialog-close"
                ng-click="cancel()"
                ng-disabled="comics.loading"
            ><?= $this->translate('Cancel'); ?></button>
        </div>
    </form>
</div>
</script>
