<script type="text/ng-template" id="adminComicsEdit">
<div ng-controller="ComicsEditController">
    <form name="adminComicsEdit">
        <h2><?= $this->translate('Create comics'); ?></h2>
        <div class="row">
            <div class="form-group col-lg-6">
                <label for="new-comics-title"><?= $this->translate('Title (required):'); ?></label>
                <input
                    class="form-control"
                    type="text"
                    name="new-comics-title"
                    id="new-comics-title"
                    ng-required="true"
                    ng-trim="true"
                    ng-minlength="1"
                    ng-model="comics.editedEntity.title"
                    ng-disabled="comics.loading"
                >
            </div>
            <div class="form-group col-lg-6">
                <label for="new-comics-slug"><?= $this->translate('Slug (required):'); ?></label>
                <input
                    class="form-control"
                    type="text"
                    name="new-comics-slug"
                    id="new-comics-slug"
                    ng-required="true"
                    ng-trim="true"
                    ng-minlength="1"
                    ng-model="comics.editedEntity.slug.slug"
                    ng-disabled="comics.loading"
                >
            </div>
        </div>
        <div class="row">
            <div class="form-group col-lg-6">
                <label for="new-comics-tagline"><?= $this->translate('Tagline (optional):'); ?></label>
                <input
                    class="form-control"
                    type="text"
                    name="new-comics-tagline"
                    id="new-comics-tagline"
                    ng-model="comics.editedEntity.tagline"
                    ng-disabled="comics.loading"
                >
            </div>
            <div class="form-group col-lg-6">
                <label for="new-comics-tagline"><?= $this->translate('Author (optional):'); ?></label>
                <ui-select ng-model="authors.selected" theme="bootstrap" ng-disabled="comics.loading">
                    <ui-select-match>{{$select.selected.name}}</ui-select-match>
                    <ui-select-choices repeat="author in authors | filter: $select.search">
                        <div ng-bind="author.name | highlight: $select.search"></div>
                    </ui-select-choices>
                </ui-select>
            </div>
        </div>
        <div class="row">
        <div class="form-group col-lg-12">
            <label for="new-comics-description"><?= $this->translate('Description (optional):'); ?></label>
            <textarea
                class="form-control"
                type="text"
                name="new-comics-description"
                id="new-comics-description"
                ng-model="comics.editedEntity.description"
                ng-disabled="comics.loading"
            ></textarea>
        </div>
        </div>
        <div class="form-group actions">
            <button
                class="btn btn-success pull-right"
                ng-disabled="adminComicsEdit.$invalid || comics.loading"
                ng-click="save()"
                ng-show="comics.editingNew()"
            ><?= $this->translate('Create'); ?></button>
            <button
                class="btn btn-success pull-right"
                ng-disabled="adminComicsEdit.$invalid || comics.loading"
                ng-click="save()"
                ng-show="!comics.editingNew()"
            ><?= $this->translate('Save'); ?></button>
            <button class="btn btn-danger pull-left" ng-click="cancel()"><?= $this->translate('Cancel'); ?></button>
        </div>
    </form>
</div>
</script>
