<script type="text/ng-template" id="adminComicsList">
    <div class="comics-list-loading" ng-show="!comics.loaded" ng-include="'loading'"></div>
    <div ng-show="comics.loaded && comics.list.length === 0" class="alert alert-info text-center">
        <?= $this->translate('There are no comics yet.'); ?>
    </div>
    <ul class="list-group comics" ng-show="comics.loaded">
        <li
            class="list-group-item"
            ng-repeat="entity in comics.list | orderBy:'id':true"
            ng-class="{active: activated(entity)}"
            ng-click="activate(entity)"
            >
            <div class="clearfix">
                <h3 class="title" ng-bind="entity.title">
                    <small><?= sprintf($this->translate('(%s)'), '<span ng-bind="entity.url"></span>'); ?></small>
                </h3>
            </div>
            <div class="clearfix" ng-show="activated(entity)">
                <hr>
                <div class="btn-group" role="group">
                    <button
                        type="button"
                        class="btn btn-xs btn-success comics-edit-open-dialog"
                        ng-disabled="strips.editing() || strips.loadingEntity"
                        ng-click="$event.stopPropagation();openComicEditDialog(entity)"
                    >
                        <?= $this->translate('Edit'); ?>
                        <i class="glyphicon glyphicon-pencil"></i>
                    </button>
                    <button
                        type="button"
                        class="btn btn-xs btn-danger comics-delete"
                        ng-disabled="strips.editing() || strips.loadingEntity"
                        ng-click="$event.stopPropagation();openComicDeleteDialog(entity);"
                    >
                        <?= $this->translate('Delete'); ?>
                        <i class="glyphicon glyphicon-remove"></i>
                    </button>
                </div>
            </div>
        </li>
    </ul>
</script>